### ISSUE TITLE
An error occurred while using a custom download size range in the request header

### ISSUE THREAD

**Issue by Skyline5723** [mjishnu/pypdl#28]
os: windows 10 22H2
python version: 3.10.11
pypdl version: 1.4.5

All the code：
```python
from pypdl import Pypdl

dl = Pypdl(allow_reuse=False, headers={
    'Accept': '*/*',
    'Connection': 'keep-alive',
    'Range': 'bytes=0-52428800',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
})
dl.start(
    url='https://xx.xx.com/xx.mp4',
    file_path='xx.mp4',
    segments=20,
    overwrite=False,
    retries=3,
    display=True,
    block=True
)
dl.shutdown()
```
Error in log file:
```python
(Pypdl)  17-12-24 16:10:30 - ERROR: (Exception) [Failed to get header (Status: 206, Reason: Partial Content)]
Traceback (most recent call last):
  File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 130, in download
    result = self._execute(
  File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 213, in _execute
    file_path, multisegment, etag = self._get_info(
  File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 267, in _get_info
    header = asyncio.run(self._get_header(url))
  File ".pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 297, in _get_header
    raise Exception(
Exception: Failed to get header (Status: 206, Reason: Partial Content)
```

When I deleted the Range key`'Range': 'bytes=0-52428800'` in headers, the download worked fine.
Is there a way I can customize the size of the download file?

**Comment by mjishnu** [comment]
> os: windows 10 22H2 python version: 3.10.11 pypdl version: 1.4.5
> 
> All the code：
> 
> ```python
> from pypdl import Pypdl
> 
> dl = Pypdl(allow_reuse=False, headers={
>     'Accept': '*/*',
>     'Connection': 'keep-alive',
>     'Range': 'bytes=0-52428800',
>     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
> })
> dl.start(
>     url='https://xx.xx.com/xx.mp4',
>     file_path='xx.mp4',
>     segments=20,
>     overwrite=False,
>     retries=3,
>     display=True,
>     block=True
> )
> dl.shutdown()
> ```
> 
> Error in log file:
> 
> ```python
> (Pypdl)  17-12-24 16:10:30 - ERROR: (Exception) [Failed to get header (Status: 206, Reason: Partial Content)]
> Traceback (most recent call last):
>   File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 130, in download
>     result = self._execute(
>   File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 213, in _execute
>     file_path, multisegment, etag = self._get_info(
>   File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 267, in _get_info
>     header = asyncio.run(self._get_header(url))
>   File ".pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File ".pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
>     return future.result()
>   File ".venv\lib\site-packages\pypdl\pypdl_manager.py", line 297, in _get_header
>     raise Exception(
> Exception: Failed to get header (Status: 206, Reason: Partial Content)
> ```
> 
> When I deleted the Range key`'Range': 'bytes=0-52428800'` in headers, the download worked fine. Is there a way I can customize the size of the download file?

hey i have fixed this in the latest version you can check it out at [https://test.pypi.org/project/pypdl/](https://test.pypi.org/project/pypdl/)
